### ISSUE TITLE
Summary section shows "undefined" and constant "Loading.." text when clicking the "Summary" button on non-case-related entries

### ISSUE THREAD

**Issue by sweatyeti** [miklopz/timekeep#1]
Repro:
Click on the "Summary" button for a "General Administration" event, and this occurs:

in the entries table, it just has "Loading..."

below the entries table, it has:
Total labor time for this case today is undefined. 
However, you have not logged undefined yet.

Clicking "Log all entries" changes the button text to "saving..." persistently until the page is refreshed.

**Comment by miklopz** [comment]
Issue is caused by the button calling a non-existent API. Non-scorecard type of labor, for now, will not have a summarized view as the summary can be seen in the bottom of the table. This will be corrected next commit.
